name: AMI Assign Template Workflow

on:
  workflow_call:
    inputs:
      TOOLKIT_VERSION:
        description: 'Version of the Ansible Automation Toolkit'
        required: false
        default: 'default'
        type: string
      ROLE:
        required: true
        type: string
      REGION:
        description: 'AWS region for assignment (e.g., il-central-1)'
        required: true
        type: string
      MAKE_DEFAULT_VERSION:
        description: 'Make Default Version (true/false)'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  ami_assign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "${{ inputs.ROLE }}"
          aws-region: "${{ inputs.REGION }}"

      - name: Download assign_ami_to_template_bulk.sh script
        run: |
          TOOLKIT_VERSION="${{ inputs.TOOLKIT_VERSION }}"
          echo "Downloading assign_ami_to_template_bulk.sh script from toolkit version $TOOLKIT_VERSION..."
          wget https://raw.githubusercontent.com/inqwise/ansible-automation-toolkit/${TOOLKIT_VERSION}/ami/assign_ami_to_template_bulk.sh -O assign_ami_to_template_bulk.sh
          chmod +x assign_ami_to_template_bulk.sh
          echo "assign_ami_to_template_bulk.sh downloaded and made executable."

      - name: Assign AMIs to Templates
        run: |
          # Set variables with defaults based on trigger
          REGION="${{ inputs.REGION }}"
          TOOLKIT_VERSION="${{ inputs.TOOLKIT_VERSION }}"
          MAKE_DEFAULT_VERSION="${{ inputs.MAKE_DEFAULT_VERSION }}"

          echo "Region: $REGION"
          echo "Toolkit Version: $TOOLKIT_VERSION"
          echo "Make Default Version: $MAKE_DEFAULT_VERSION"

          # Build the command
          CMD="./assign_ami_to_template_bulk.sh --region \"$REGION\" --toolkit-version \"$TOOLKIT_VERSION\""

          # Add --make-default-version if set to true
          if [[ "$MAKE_DEFAULT_VERSION" == "true" ]]; then
            CMD+=" --make-default-version"
          fi

          echo "Executing command: $CMD"
          eval "$CMD"

          echo "AMI assignment process completed."